"""
report_generator.py
-------------------
Generates grading output in three formats:
  1. Individual .txt feedback files (one per student)
  2. CSV summary spreadsheet (all students in one file)
  3. HTML dashboard (visual, shareable)
"""

import csv
import os
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional


# ── Individual feedback files ─────────────────────────────────────────────────

def write_student_feedback(result: Dict, output_dir: str) -> str:
    """
    Write a detailed plain-text feedback file for a single student.
    Returns the path to the created file.
    """
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    safe_name = _safe_filename(result["student_name"])
    file_path = os.path.join(output_dir, f"{safe_name}_feedback.txt")

    lines = []
    _line = lines.append

    _line("=" * 70)
    _line(f"  ASSIGNMENT FEEDBACK — AI FOR ANALYTICS")
    _line("=" * 70)
    _line(f"  Student : {result['student_name']}")
    _line(f"  File    : {result.get('file', 'N/A')}")
    _line(f"  Date    : {datetime.now().strftime('%B %d, %Y')}")
    _line("=" * 70)
    _line("")

    # Score summary
    _line("SCORE SUMMARY")
    _line("-" * 40)
    total = result.get("total_score", 0)
    max_s = result.get("max_score", 100)
    pct   = result.get("percentage", 0.0)
    grade = result.get("letter_grade", "N/A")
    _line(f"  Total Score  : {total} / {max_s} points")
    _line(f"  Percentage   : {pct}%")
    _line(f"  Letter Grade : {grade}")
    _line("")

    # Overall summary
    _line("OVERALL FEEDBACK")
    _line("-" * 40)
    _line(_wrap(result.get("overall_summary", ""), width=68))
    _line("")

    # Per-criterion breakdown
    criteria = result.get("criteria", [])
    if criteria:
        _line("CRITERION BREAKDOWN")
        _line("-" * 40)
        for c in criteria:
            awarded = c.get("awarded_points", 0)
            maximum = c.get("max_points", 0)
            _line(f"  [{awarded}/{maximum}]  {c.get('name', 'Unknown')}")
            feedback_text = c.get("feedback", "")
            if feedback_text:
                for wrapped_line in _wrap(feedback_text, width=66, indent="        ").split("\n"):
                    _line(wrapped_line)
            _line("")

    # Strengths
    strengths = result.get("strengths", [])
    if strengths:
        _line("STRENGTHS")
        _line("-" * 40)
        for s in strengths:
            _line(f"  ✓  {s}")
        _line("")

    # Areas for improvement
    areas = result.get("areas_for_improvement", [])
    if areas:
        _line("AREAS FOR IMPROVEMENT")
        _line("-" * 40)
        for a in areas:
            _line(f"  •  {a}")
        _line("")

    # Actionable suggestions
    suggestions = result.get("actionable_suggestions", "")
    if suggestions:
        _line("ACTIONABLE SUGGESTIONS")
        _line("-" * 40)
        _line(_wrap(suggestions, width=68))
        _line("")

    _line("=" * 70)
    _line("  Generated by AI Grading Assistant — AI for Analytics Course")
    _line("=" * 70)

    with open(file_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return file_path


# ── CSV summary ───────────────────────────────────────────────────────────────

def write_csv_summary(results: List[Dict], output_dir: str) -> str:
    """
    Write a CSV summary with one row per student.
    Returns the path to the created file.
    """
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    file_path = os.path.join(output_dir, f"grading_summary_{timestamp}.csv")

    # Collect all unique criterion names across all results
    all_criteria: List[str] = []
    for r in results:
        for c in r.get("criteria", []):
            name = c.get("name", "")
            if name and name not in all_criteria:
                all_criteria.append(name)

    # Build CSV header
    base_fields = [
        "Student Name",
        "Submission File",
        "Total Score",
        "Max Score",
        "Percentage (%)",
        "Letter Grade",
    ]
    # Add one column per criterion: "Criterion Name (score)"
    criterion_fields = [f"{c} (pts)" for c in all_criteria]
    header = base_fields + criterion_fields + ["Overall Summary", "Strengths", "Areas for Improvement"]

    rows = []
    for r in results:
        row = {
            "Student Name": r.get("student_name", ""),
            "Submission File": r.get("file", ""),
            "Total Score": r.get("total_score", 0),
            "Max Score": r.get("max_score", 100),
            "Percentage (%)": r.get("percentage", 0.0),
            "Letter Grade": r.get("letter_grade", "N/A"),
            "Overall Summary": r.get("overall_summary", ""),
            "Strengths": "; ".join(r.get("strengths", [])),
            "Areas for Improvement": "; ".join(r.get("areas_for_improvement", [])),
        }
        # Fill criterion scores
        criteria_lookup = {c.get("name", ""): c for c in r.get("criteria", [])}
        for cname in all_criteria:
            c = criteria_lookup.get(cname, {})
            awarded = c.get("awarded_points", "N/A")
            maximum = c.get("max_points", "")
            row[f"{cname} (pts)"] = f"{awarded}/{maximum}" if maximum else str(awarded)
        rows.append(row)

    with open(file_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=header)
        writer.writeheader()
        writer.writerows(rows)

    return file_path


# ── HTML dashboard ────────────────────────────────────────────────────────────

def write_html_report(results: List[Dict], output_dir: str, assignment_name: str = "Assignment") -> str:
    """
    Generate a clean, self-contained HTML dashboard.
    Returns the path to the created file.
    """
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    file_path = os.path.join(output_dir, f"grading_report_{timestamp}.html")

    # Calculate class stats
    scores = [r.get("percentage", 0) for r in results if not r.get("error")]
    class_avg = round(sum(scores) / len(scores), 1) if scores else 0
    highest   = max(scores) if scores else 0
    lowest    = min(scores) if scores else 0

    grade_counts = {"A": 0, "B": 0, "C": 0, "D": 0, "F": 0, "N/A": 0}
    for r in results:
        lg = r.get("letter_grade", "N/A")
        bucket = lg[0] if lg and lg[0] in grade_counts else "N/A"
        grade_counts[bucket] += 1

    # Build student rows
    student_rows_html = ""
    for r in results:
        pct  = r.get("percentage", 0)
        bar_color = _grade_color(r.get("letter_grade", "N/A"))
        criteria_cells = "".join(
            f"<td>{c.get('awarded_points', 'N/A')}/{c.get('max_points', '?')}</td>"
            for c in r.get("criteria", [])
        )

        # Strengths & improvements
        strengths_list = "".join(
            f"<li>✓ {s}</li>" for s in r.get("strengths", [])
        )
        areas_list = "".join(
            f"<li>• {a}</li>" for a in r.get("areas_for_improvement", [])
        )
        suggestions = r.get("actionable_suggestions", "").replace("\n", "<br>")

        student_rows_html += f"""
        <div class="student-card" id="student-{_safe_filename(r['student_name'])}">
            <div class="student-header" onclick="toggleCard(this)">
                <div class="student-info">
                    <span class="student-name">{r['student_name']}</span>
                    <span class="student-file">{r.get('file', '')}</span>
                </div>
                <div class="student-score">
                    <span class="score-badge" style="background:{bar_color}">{r.get('letter_grade','N/A')}</span>
                    <span class="score-number">{r.get('total_score',0)}/{r.get('max_score',100)} pts &nbsp;({pct}%)</span>
                    <span class="toggle-icon">▼</span>
                </div>
            </div>
            <div class="student-body" style="display:none;">
                <div class="score-bar-container">
                    <div class="score-bar" style="width:{pct}%;background:{bar_color}"></div>
                </div>
                <p class="overall-summary">{r.get('overall_summary','')}</p>

                <div class="detail-grid">
                    <div class="detail-col">
                        <h4>Strengths</h4>
                        <ul>{strengths_list or '<li>None listed</li>'}</ul>
                    </div>
                    <div class="detail-col">
                        <h4>Areas for Improvement</h4>
                        <ul>{areas_list or '<li>None listed</li>'}</ul>
                    </div>
                </div>

                {"<h4>Criterion Breakdown</h4>" + _criteria_table(r.get('criteria', [])) if r.get('criteria') else ""}

                <div class="suggestions-box">
                    <h4>Actionable Suggestions</h4>
                    <p>{suggestions}</p>
                </div>
            </div>
        </div>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Grading Report — {assignment_name}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
          background: #f0f4f8; color: #2d3748; }}
  .container {{ max-width: 960px; margin: 0 auto; padding: 24px 16px; }}

  /* Header */
  .page-header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                  color: white; border-radius: 12px; padding: 28px 32px; margin-bottom: 24px; }}
  .page-header h1 {{ font-size: 1.8rem; margin-bottom: 6px; }}
  .page-header p  {{ opacity: 0.85; font-size: 0.95rem; }}

  /* Stats bar */
  .stats-row {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-bottom: 24px; }}
  .stat-card {{ background: white; border-radius: 10px; padding: 18px 20px;
                box-shadow: 0 1px 4px rgba(0,0,0,.08); text-align: center; }}
  .stat-value {{ font-size: 1.8rem; font-weight: 700; color: #667eea; }}
  .stat-label {{ font-size: 0.8rem; color: #718096; margin-top: 4px; }}

  /* Student cards */
  .student-card {{ background: white; border-radius: 10px; margin-bottom: 14px;
                   box-shadow: 0 1px 4px rgba(0,0,0,.08); overflow: hidden; }}
  .student-header {{ display: flex; justify-content: space-between; align-items: center;
                     padding: 16px 20px; cursor: pointer; user-select: none; }}
  .student-header:hover {{ background: #f7fafc; }}
  .student-name {{ font-weight: 600; font-size: 1.05rem; }}
  .student-file {{ color: #718096; font-size: 0.8rem; margin-left: 10px; }}
  .score-badge {{ display: inline-block; padding: 4px 10px; border-radius: 20px;
                  color: white; font-weight: 700; font-size: 0.9rem; margin-right: 8px; }}
  .score-number {{ color: #4a5568; font-size: 0.9rem; }}
  .toggle-icon {{ margin-left: 12px; color: #a0aec0; }}

  .student-body {{ padding: 0 20px 20px; border-top: 1px solid #e2e8f0; }}
  .score-bar-container {{ background: #edf2f7; border-radius: 20px; height: 8px; margin: 14px 0 12px; }}
  .score-bar {{ height: 8px; border-radius: 20px; transition: width .4s; }}

  .overall-summary {{ color: #4a5568; line-height: 1.6; margin-bottom: 16px; }}

  .detail-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 16px; }}
  .detail-col h4 {{ font-size: 0.85rem; text-transform: uppercase; color: #718096;
                    letter-spacing: .05em; margin-bottom: 8px; }}
  .detail-col ul {{ list-style: none; padding: 0; }}
  .detail-col li {{ font-size: 0.9rem; color: #4a5568; padding: 3px 0; line-height: 1.4; }}

  /* Criteria table */
  .criteria-table {{ width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 0.9rem; }}
  .criteria-table th {{ background: #f7fafc; padding: 8px 12px; text-align: left;
                         font-size: 0.8rem; color: #718096; border-bottom: 2px solid #e2e8f0; }}
  .criteria-table td {{ padding: 9px 12px; border-bottom: 1px solid #edf2f7; vertical-align: top; }}
  .criteria-table tr:last-child td {{ border-bottom: none; }}

  .suggestions-box {{ background: #ebf8ff; border-left: 4px solid #63b3ed;
                      border-radius: 0 8px 8px 0; padding: 14px 16px; margin-top: 16px; }}
  .suggestions-box h4 {{ color: #2b6cb0; font-size: 0.85rem; text-transform: uppercase;
                          letter-spacing: .05em; margin-bottom: 8px; }}
  .suggestions-box p {{ color: #2c5282; font-size: 0.9rem; line-height: 1.6; }}

  .section-title {{ font-size: 0.85rem; text-transform: uppercase; color: #718096;
                    letter-spacing: .08em; margin-bottom: 12px; }}
  h4 {{ font-size: 0.9rem; color: #4a5568; margin-bottom: 8px; }}

  footer {{ text-align: center; color: #a0aec0; font-size: 0.8rem; margin-top: 24px; padding-bottom: 16px; }}
  @media (max-width: 600px) {{
    .stats-row {{ grid-template-columns: repeat(2, 1fr); }}
    .detail-grid {{ grid-template-columns: 1fr; }}
    .student-header {{ flex-wrap: wrap; }}
  }}
</style>
</head>
<body>
<div class="container">

  <div class="page-header">
    <h1>📊 Grading Report</h1>
    <p>{assignment_name} &nbsp;·&nbsp; AI for Analytics &nbsp;·&nbsp;
       Generated {datetime.now().strftime('%B %d, %Y at %I:%M %p')}</p>
  </div>

  <div class="stats-row">
    <div class="stat-card">
      <div class="stat-value">{len(results)}</div>
      <div class="stat-label">Students</div>
    </div>
    <div class="stat-card">
      <div class="stat-value">{class_avg}%</div>
      <div class="stat-label">Class Average</div>
    </div>
    <div class="stat-card">
      <div class="stat-value">{highest}%</div>
      <div class="stat-label">Highest Score</div>
    </div>
    <div class="stat-card">
      <div class="stat-value">{lowest}%</div>
      <div class="stat-label">Lowest Score</div>
    </div>
  </div>

  <p class="section-title">Student Results — click a row to expand</p>
  {student_rows_html}

  <footer>AI Grading Assistant · AI for Analytics Course · For TA Use Only</footer>
</div>

<script>
function toggleCard(headerEl) {{
  const body = headerEl.nextElementSibling;
  const icon = headerEl.querySelector('.toggle-icon');
  const isOpen = body.style.display !== 'none';
  body.style.display = isOpen ? 'none' : 'block';
  icon.textContent = isOpen ? '▼' : '▲';
}}
// Open first card by default
document.addEventListener('DOMContentLoaded', () => {{
  const firstHeader = document.querySelector('.student-header');
  if (firstHeader) toggleCard(firstHeader);
}});
</script>
</body>
</html>"""

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(html)

    return file_path


# ── Utilities ─────────────────────────────────────────────────────────────────

def _criteria_table(criteria: List[Dict]) -> str:
    rows = ""
    for c in criteria:
        awarded = c.get("awarded_points", "N/A")
        maximum = c.get("max_points", "?")
        pct = round((awarded / maximum) * 100) if isinstance(awarded, (int, float)) and maximum else 0
        color = _grade_color_pct(pct)
        rows += f"""<tr>
          <td><strong>{c.get('name','')}</strong></td>
          <td style="white-space:nowrap;color:{color};font-weight:600">{awarded}/{maximum}</td>
          <td>{c.get('feedback','')}</td>
        </tr>"""
    return f"""<table class="criteria-table">
      <thead><tr><th>Criterion</th><th>Score</th><th>Feedback</th></tr></thead>
      <tbody>{rows}</tbody>
    </table>"""


def _grade_color(letter_grade: str) -> str:
    mapping = {
        "A+": "#38a169", "A": "#38a169", "A-": "#48bb78",
        "B+": "#4299e1", "B": "#4299e1", "B-": "#63b3ed",
        "C+": "#ed8936", "C": "#ed8936", "C-": "#f6ad55",
        "D":  "#e53e3e",
        "F":  "#c53030",
    }
    return mapping.get(letter_grade, "#718096")


def _grade_color_pct(pct: float) -> str:
    if pct >= 90: return "#38a169"
    if pct >= 80: return "#4299e1"
    if pct >= 70: return "#ed8936"
    return "#e53e3e"


def _safe_filename(name: str) -> str:
    import re
    return re.sub(r"[^\w\-]", "_", name).strip("_")


def _wrap(text: str, width: int = 70, indent: str = "") -> str:
    """Simple word-wrap for plain text output."""
    import textwrap
    return textwrap.fill(text, width=width, initial_indent=indent, subsequent_indent=indent)
